### ISSUE TITLE
Segfault when writing OBJ TexCoords

### ISSUE THREAD

**Issue by nh2** [cnr-isti-vclab/meshlab#1174]
I have a 13 MB PLY file with texture that can be successfully loaded by Meshlab, but when I save it as OBJ, Meshlab segfaults when saving texcoords:

![image](https://user-images.githubusercontent.com/399535/145915686-c18d4477-4029-4c05-a341-92551d23b106.png)

`gdb` output (on MeshLab 2021.10 FlatPak` from the website download):

```
Thread 1 "meshlab" received signal SIGSEGV, Segmentation fault.
0x00007fffbd521998 in vcg::tri::io::Materials<CMeshO>::CreateNewMaterial(CMeshO const&, std::vector<vcg::tri::io::Material, std::allocator<vcg::tri::io::Material> >&, CFaceO const&) () from /tmp/.mount_MeshLaNHKodD/usr/lib/meshlab/plugins/libio_base.so
(gdb) bt
#0  0x00007fffbd521998 in vcg::tri::io::Materials<CMeshO>::CreateNewMaterial(CMeshO const&, std::vector<vcg::tri::io::Material, std::allocator<vcg::tri::io::Material> >&, CFaceO const&) () from /tmp/.mount_MeshLaNHKodD/usr/lib/meshlab/plugins/libio_base.so
#1  0x00007fffbd533b07 in vcg::tri::io::ExporterOBJ<CMeshO>::Save(CMeshO&, char const*, int, bool, bool (*)(int, char const*)) () from /tmp/.mount_MeshLaNHKodD/usr/lib/meshlab/plugins/libio_base.so
#2  0x00007fffbd510435 in BaseMeshIOPlugin::save(QString const&, QString const&, MeshModel&, int, RichParameterList const&, bool (*)(int, char const*)) () from /tmp/.mount_MeshLaNHKodD/usr/lib/meshlab/plugins/libio_base.so
#3  0x00005555555dac7c in MainWindow::exportMesh(QString, MeshModel*, bool) ()
#4  0x00005555555dc349 in MainWindow::saveAs(QString, bool) ()
#5  0x00005555555a4dcd in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#6  0x00007ffff59c3ddf in void doActivate<false>(QObject*, int, void**) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Core.so.5
#7  0x00007ffff6bb0672 in QAction::triggered(bool) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Widgets.so.5
#8  0x00007ffff6bb2a9e in QAction::activate(QAction::ActionEvent) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Widgets.so.5
#9  0x00007ffff6bb339d in QAction::event(QEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Widgets.so.5
#10 0x00007ffff6bb643c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff6bbcf20 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff7bae8eb in MeshLabApplication::notify(QObject*, QEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/lib/meshlab/libmeshlab-common.so
#13 0x00007ffff598b808 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Core.so.5
#14 0x00007ffff62bfd66 in QShortcutMap::dispatchEvent(QKeyEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Gui.so.5
#15 0x00007ffff62c07e9 in QShortcutMap::tryShortcut(QKeyEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Gui.so.5
#16 0x00007ffff62723a2 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Gui.so.5
#17 0x00007ffff628de64 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Gui.so.5
#18 0x00007ffff6292935 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Gui.so.5
#19 0x00007ffff626e8ab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Gui.so.5
#20 0x00007fffee8a269a in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /tmp/.mount_MeshLaNHKodD/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#21 0x00007ffff1508537 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff1508770 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff15087fc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff59e71cc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Core.so.5
#25 0x00007ffff598a21a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Core.so.5
#26 0x00007ffff59931d3 in QCoreApplication::exec() () from /tmp/.mount_MeshLaNHKodD/usr/bin/../lib/libQt5Core.so.5
#27 0x00005555555a10b3 in main ()
```

`valgrind` output (tried here MeshLab 2020.12 from `nixpkgs`):

```
==1499== Invalid read of size 2
==1499==    at 0x14A3CFBB: vcg::tri::io::ExporterOBJ<CMeshO>::Save(CMeshO&, char const*, int, bool, bool (*)(int, char const*)) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/lib/meshlab/plugins/libio_base.so)
==1499==    by 0x14A07FC4: BaseMeshIOPlugin::save(QString const&, QString const&, MeshModel&, int, RichParameterList const&, bool (*)(int, char const*), QWidget*) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/lib/meshlab/plugins/libio_base.so)
==1499==    by 0x4A0B6D: MainWindow::exportMesh(QString, MeshModel*, bool) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/bin/.meshlab-wrapped)
==1499==    by 0x4A25DF: MainWindow::saveAs(QString, bool) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/bin/.meshlab-wrapped)
==1499==    by 0x44DFA0: MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/bin/.meshlab-wrapped)
==1499==    by 0x5D1A43F: ??? (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Core.so.5.15.3)
==1499==    by 0x4CEDE41: QAction::triggered(bool) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x4CF0A87: QAction::activate(QAction::ActionEvent) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x4CF1666: QAction::event(QEvent*) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x4CF476E: QApplicationPrivate::notify_helper(QObject*, QEvent*) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x48D0BE9: MeshLabApplication::notify(QObject*, QEvent*) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/lib/meshlab/libmeshlab-common.so)
==1499==    by 0x5CE3409: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Core.so.5.15.3)
==1499==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==1499== 
==1499== 
==1499== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==1499==  Access not within mapped region at address 0x8
==1499==    at 0x14A3CFBB: vcg::tri::io::ExporterOBJ<CMeshO>::Save(CMeshO&, char const*, int, bool, bool (*)(int, char const*)) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/lib/meshlab/plugins/libio_base.so)
==1499==    by 0x14A07FC4: BaseMeshIOPlugin::save(QString const&, QString const&, MeshModel&, int, RichParameterList const&, bool (*)(int, char const*), QWidget*) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/lib/meshlab/plugins/libio_base.so)
==1499==    by 0x4A0B6D: MainWindow::exportMesh(QString, MeshModel*, bool) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/bin/.meshlab-wrapped)
==1499==    by 0x4A25DF: MainWindow::saveAs(QString, bool) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/bin/.meshlab-wrapped)
==1499==    by 0x44DFA0: MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/bin/.meshlab-wrapped)
==1499==    by 0x5D1A43F: ??? (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Core.so.5.15.3)
==1499==    by 0x4CEDE41: QAction::triggered(bool) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x4CF0A87: QAction::activate(QAction::ActionEvent) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x4CF1666: QAction::event(QEvent*) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x4CF476E: QApplicationPrivate::notify_helper(QObject*, QEvent*) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Widgets.so.5.15.3)
==1499==    by 0x48D0BE9: MeshLabApplication::notify(QObject*, QEvent*) (in /nix/store/5x2pcwm0dpwmhnkvkdchc4dp4fcnj1xy-meshlab-2020.12/lib/meshlab/libmeshlab-common.so)
==1499==    by 0x5CE3409: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/lib/libQt5Core.so.5.15.3)
```

And same issue for `MeshLab 2021.05d` compiled from source on Ubuntu 18.04.

Unfortunately the PLY is confidential because it contains some buildings. But I could share it with Meshlab devs privately if that's OK.

I didn't manage to simplify the input further, since changing it with Blender and re-importing that into MeshLab makes the issue disappear.

The crash happens when the progress bar is at `writing vertices`, 43 %..

**Comment by alemuntoni** [comment]
Yes, you can send it to my email: muntoni.alessandro@gmail.com, thanks!

**Comment by nh2** [comment]
Thanks @alemuntoni , I've emailed it!

**Comment by alemuntoni** [comment]
Solved! Thanks for reporting @nh2!

**Comment by nh2** [comment]
@alemuntoni Thanks! That's this commit, right? https://github.com/cnr-isti-vclab/vcglib/commit/5cdefce22e377369d7c8eede0c78a6fb224b81de
