### ISSUE TITLE
[MeshLab 2022.02, Linux] Segmentation fault when loading a glTF point cloud

### ISSUE THREAD

**Issue by bchretien** [cnr-isti-vclab/meshlab#1387]
When loading a point cloud stored as a GLB, I get a segmentation fault. Here is the backtrace:

```
Thread 1 "meshlab" received signal SIGSEGV, Segmentation fault.
0x00007fffb08620f1 in void gltf::internal::populateTriangles<unsigned char>(MeshModel&, std::vector<CVertexO*, std::allocator<CVertexO*> > const&, unsigned char const*, unsigned int) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
(gdb) bt
#0  0x00007fffb08620f1 in void gltf::internal::populateTriangles<unsigned char>(MeshModel&, std::vector<CVertexO*, std::allocator<CVertexO*> > const&, unsigned char const*, unsigned int) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#1  0x00007fffb085ae6e in gltf::internal::loadAttribute(MeshModel&, std::vector<CVertexO*, std::allocator<CVertexO*> >&, tinygltf::Model const&, tinygltf::Primitive const&, gltf::internal::GLTF_ATTR_TYPE, int) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#2  0x00007fffb085bc14 in gltf::internal::loadMeshPrimitive(MeshModel&, int&, tinygltf::Model const&, tinygltf::Primitive const&, bool, vcg::Matrix44<float> const&, bool (*)(int, char const*), CallBackProgress&) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#3  0x00007fffb085be77 in gltf::internal::loadMesh(MeshModel&, int&, tinygltf::Mesh const&, tinygltf::Model const&, bool, vcg::Matrix44<float> const&, bool (*)(int, char const*), CallBackProgress&) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#4  0x00007fffb085bfe6 in gltf::internal::loadMeshesWhileTraversingNodes(tinygltf::Model const&, std::_List_const_iterator<MeshModel*>&, std::_List_iterator<int>&, vcg::Matrix44<float>, unsigned int, bool, bool (*)(int, char const*), CallBackProgress&) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#5  0x00007fffb085c1e3 in gltf::loadMeshes(std::__cxx11::list<MeshModel*, std::allocator<MeshModel*> > const&, std::__cxx11::list<int, std::allocator<int> >&, tinygltf::Model const&, bool, bool (*)(int, char const*)) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#6  0x00007fffb0832e3b in IOglTFPlugin::open(QString const&, QString const&, std::__cxx11::list<MeshModel*, std::allocator<MeshModel*> > const&, std::__cxx11::list<int, std::allocator<int> >&, RichParameterList const&, bool (*)(int, char const*)) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/plugins/libio_gltf.so
#7  0x00007ffff7c8170b in meshlab::loadMesh(QString const&, IOPlugin*, RichParameterList const&, std::__cxx11::list<MeshModel*, std::allocator<MeshModel*> > const&, std::__cxx11::list<int, std::allocator<int> >&, bool (*)(int, char const*)) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/libmeshlab-common.so
#8  0x000055555548a670 in MainWindow::importMesh(QString) ()
#9  0x000055555548bb53 in MainWindow::importMeshWithLayerManagement(QString) ()
#10 0x000055555548bc68 in MainWindow::openRecentMesh() ()
#11 0x0000555555450686 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#12 0x00007ffff52d5ddf in void doActivate<false>(QObject*, int, void**) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Core.so.5
#13 0x00007ffff675d672 in QAction::triggered(bool) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#14 0x00007ffff675fa9e in QAction::activate(QAction::ActionEvent) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#15 0x00007ffff68cf53a in QMenuPrivate::activateCausedStack(QVector<QPointer<QWidget> > const&, QAction*, QAction::ActionEvent, bool) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#16 0x00007ffff68d6666 in QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff68d77c0 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff67a1740 in QWidget::event(QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff68d9cdb in QMenu::event(QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff676343c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff676a1f8 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#22 0x00007ffff7c874bb in MeshLabApplication::notify(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/libmeshlab-common.so
#23 0x00007ffff529d808 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Core.so.5
#24 0x00007ffff676953a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#25 0x00007ffff67bacda in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#26 0x00007ffff67bdcf3 in QWidgetWindow::event(QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff676343c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff6769f20 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff7c874bb in MeshLabApplication::notify(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/lib/meshlab/libmeshlab-common.so
#30 0x00007ffff529d808 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Core.so.5
#31 0x00007ffff5d6f56d in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Gui.so.5
#32 0x00007ffff5d70955 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Gui.so.5
#33 0x00007ffff5d4c8ab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Gui.so.5
#34 0x00007fffefe6569a in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /tmp/.mount_MeshLaqNa84e/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#35 0x00007ffff731bd3b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff73706c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff73193e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff52f91cc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Core.so.5
#39 0x00007ffff529c21a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Core.so.5
#40 0x00007ffff52a51d3 in QCoreApplication::exec() () from /tmp/.mount_MeshLaqNa84e/usr/bin/../lib/libQt5Core.so.5
#41 0x000055555544ca23 in main ()
```

I used `MeshLab2022.02-linux.AppImage`. Looking quickly at the code, the problem might be [here](https://github.com/cnr-isti-vclab/meshlab/blob/108e98b7b6be34219cf05543e8aac1660adf03b3/src/meshlabplugins/io_gltf/gltf_loader.cpp#L726): we try to build triangles, assuming that we have `3*k` vertices, which is obviously not necessarily the case. I don't understand the motivation behind this `else` block.

**Comment by alemuntoni** [comment]
This issue could have been already solved. Could you please try the last nightly build from the devel branch? You can find it [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/4913018818). 

If the issue still persists, please share the input model.

**Comment by alemuntoni** [comment]
@RichardBowenGM your file loads with the nightly version of MeshLab.
I can confirm the issue on the glb provided by @bchretien. I'll try to fix it
