### ISSUE TITLE
Crash on "Parameterization (+UV) from registered rasters" 

### ISSUE THREAD

**Issue by Moult** [cnr-isti-vclab/meshlab#343]
I am experiencing exactly the same bug in: https://sourceforge.net/p/meshlab/bugs/459/ with the exception that the original author created the dataset in VSFM and I am creating it with COLMAP.

1. Select Filters -> Texture -> Parameterization from registered rasters" (+UV option also triggers this)
2. Click apply (leaving all defaults)

Backtrace of crash:

```
meshlab: ../../../../vcglib/wrap/glw/././texture2d.h:110: void glw::Texture2D::setSampleMode(GLenum, GLint, const glw::TextureSampleMode&): Assertion 'this->isValid()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff41b0067 in GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56 ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0 0x00007ffff41b0067 in GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1 0x00007ffff41b1448 in GI_abort () at abort.c:89
#2 0x00007ffff41a9266 in assert_fail_base (fmt=0x7ffff42e2238 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
assertion=assertion@entry=0x7fffdd437785 "this->isValid()",
file=file@entry=0x7fffdd437330 "../../../../vcglib/wrap/glw/././texture2d.h", line=line@entry=110,
function=function@entry=0x7fffdd438580 <glw::Texture2D::setSampleMode(unsigned int,="" int,="" glw::TextureSampleMode="" const&)::__PRETTY_FUNCTION__=""> "void glw::Texture2D::setSampleMode(GLenum, GLint, const glw::TextureSampleMode&)") at assert.c:92
#3 0x00007ffff41a9312 in GI_assert_fail (assertion=0x7fffdd437785 "this->isValid()",
file=0x7fffdd437330 "../../../../vcglib/wrap/glw/././texture2d.h", line=110,
function=0x7fffdd438580 <glw::Texture2D::setSampleMode(unsigned int,="" int,="" glw::TextureSampleMode="" const&)::__PRETTY_FUNCTION__=""> "void glw::Texture2D::setSampleMode(GLenum, GLint, const glw::TextureSampleMode&)") at assert.c:101
#4 0x00007fffdd4029d0 in glw::Texture2D::setSampleMode(unsigned int, int, glw::TextureSampleMode const&) [clone .part.19] ()
from /home/sea/pbin/ml/meshlab/src/distrib/plugins/libfilter_img_patch_param.so
#5 0x00007fffdd4269db in glw::createTexture2D(glw::Context&, unsigned int, int, int, unsigned int, unsigned int, void const, glw::TextureSampleMode const&) () from /home/sea/pbin/ml/meshlab/src/distrib/plugins/libfilter_img_patch_param.so
#6 0x00007fffdd41f3f8 in VisibilityCheck_ShadowMap::setupShadowTexture() ()
from /home/sea/pbin/ml/meshlab/src/distrib/plugins/libfilter_img_patch_param.so
#7 0x00007fffdd41e0c5 in VisibleSet::VisibleSet(glw::Context&, CMeshO&, QList<RasterModel*>&, int) ()
from /home/sea/pbin/ml/meshlab/src/distrib/plugins/libfilter_img_patch_param.so
#8 0x00007fffdd40a3f7 in FilterImgPatchParamPlugin::patchBasedTextureParameterization(QMap<RasterModel*, QVector<Patch=""> >&, QVector<Patch>&, CMeshO&, QList<RasterModel*>&, RichParameterSet&) ()
from /home/sea/pbin/ml/meshlab/src/distrib/plugins/libfilter_img_patch_param.so
#9 0x00007fffdd40bd7e in FilterImgPatchParamPlugin::applyFilter(QAction, MeshDocument&, RichParameterSet&, bool ()(int, char const)) () from /home/sea/pbin/ml/meshlab/src/distrib/plugins/libfilter_img_patch_param.so
#10 0x0000000000457df0 in MainWindow::executeFilter(QAction, RichParameterSet&, bool) ()
#11 0x00000000004abd5a in MeshlabStdDialog::applyClick() ()
#12 0x00007ffff543071c in QMetaObject::activate(QObject, QMetaObject const, int, void) ()
from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff632eb92 in QAbstractButton::clicked(bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007ffff606d743 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007ffff606eaf4 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#16 0x00007ffff606ec04 in QAbstractButton::mouseReleaseEvent(QMouseEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007ffff5cef748 in QWidget::event(QEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007ffff5c9c48c in QApplicationPrivate::notify_helper(QObject, QEvent) ()
from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff5ca310f in QApplication::notify(QObject, QEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007ffff7b553e6 in MeshLabApplication::notify(QObject, QEvent) ()
kio_file(18592) kdemain: Doneb/src/distrib/libcommon.so.1
#21 0x00007ffff541b71d in QCoreApplication::notifyInternal(QObject, QEvent) ()
from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00007ffff5ca276f in QApplicationPrivate::sendMouseEvent(QWidget, QMouseEvent, QWidget, QWidget, QWidget, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#23 0x00007ffff5d19432 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#24 0x00007ffff5d17e2c in QApplication::x11ProcessEvent(_XEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffff5d40ed2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#26 0x00007ffff3063c5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff3063f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff3063ffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff544ad37 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#30 0x00007ffff5d40f96 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffff541a271 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#32 0x00007ffff541a5d5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
from /usr/lib/x86_64-linux-gnu/libQtC> ore.so.4
#33 0x00007ffff5420059 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#34 0x000000000042e885 in main ()
```

**Comment by Moult** [comment]
I sincerely apologise, I forgot to close this bug. The issue was the registered raster images were not in the right directory, so the file I was loading was referring to the wrong image location.

My bad. PEBKAC.
