### ISSUE TITLE
Crash (assertion failure) when running remeshing on model that loads fine

### ISSUE THREAD

**Issue by rpavlik** [cnr-isti-vclab/meshlab#637]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [X] Linux
- [ ] Every platform

I'm using the 2020.03 release as I packaged for debian.

#### What type of issue is?
- [ ] bug or unexpected behavior
- [X] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

When I open this mesh, then go filters, remeshing, isotropic remeshing (apparently with or without adaptive), I get the following assertion and backtrace:

```
meshlab: ./vcglib/vcg/simplex/vertex/component_ocf.h:411: int vcg::vertex::MarkOcf<T>::cIMark() const [with T = vcg::Arity7<vcg::vertex::EmptyCore<CUsedTypesO>, vcg::vertex::InfoOcf, vcg::vertex::Coord3m, vcg::vertex::BitFlags, vcg::vertex::Normal3m, vcg::vertex::Qualityf, vcg::vertex::Color4b, vcg::vertex::VFAdjOcf>]: Assertion `(*this).Base().MarkEnabled' failed.

Thread 1 "meshlab" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5ece7bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5eb9535 in __GI_abort () at abort.c:79
#2  0x00007ffff5eb940f in __assert_fail_base (fmt=0x7ffff601bee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fff94fcb038 "(*this).Base().MarkEnabled", file=0x7fff94fc9820 "./vcglib/vcg/simplex/vertex/component_ocf.h", line=411, function=<optimized out>) at assert.c:92
#3  0x00007ffff5ec7102 in __GI___assert_fail
    (assertion=assertion@entry=0x7fff94fcb038 "(*this).Base().MarkEnabled", file=file@entry=0x7fff94fc9820 "./vcglib/vcg/simplex/vertex/component_ocf.h", line=line@entry=411, function=function@entry=0x7fff94fc4c60 <vcg::vertex::MarkOcf<vcg::Arity7<vcg::vertex::EmptyCore<CUsedTypesO>, vcg::vertex::InfoOcf, vcg::vertex::Coord3m, vcg::vertex::BitFlags, vcg::vertex::Normal3m, vcg::vertex::Qualityf, vcg::vertex::Color4b, vcg::vertex::VFAdjOcf> >::cIMark() const::__PRETTY_FUNCTION__> "int vcg::vertex::MarkOcf<T>::cIMark() const [with T = vcg::Arity7<vcg::vertex::EmptyCore<CUsedTypesO>, vcg::vertex::InfoOcf, vcg::vertex::Coord3m, vcg::vertex::BitFlags, vcg::vertex::Normal3m, vcg::ve"...) at assert.c:101
#4  0x00007fff94f5dc3f in vcg::vertex::MarkOcf<vcg::Arity7<vcg::vertex::EmptyCore<CUsedTypesO>, vcg::vertex::InfoOcf, vcg::vertex::Coord3m, vcg::vertex::BitFlags, vcg::vertex::Normal3m, vcg::vertex::Qualityf, vcg::vertex::Color4b, vcg::vertex::VFAdjOcf> >::cIMark() const (this=<optimized out>) at ./vcglib/vcg/space/deprecated_point3.h:130
#5  0x00007fff94f5dc3f in vcg::tri::IsMarked<CMeshO>(CMeshO&, CMeshO::ConstVertexPointer) (m=..., v=<optimized out>) at ./vcglib/vcg/complex/base.h:525
#6  0x00007fff94f5dc3f in vcg::tri::IsotropicRemeshing<CMeshO>::removeColinearFaces(CMeshO&, vcg::tri::IsotropicRemeshing<CMeshO>::Params&) (m=..., params=...) at ./vcglib/vcg/complex/algorithms/isotropic_remeshing.h:178
#7  0x00007fff94f65ab3 in vcg::tri::IsotropicRemeshing<CMeshO>::cleanMesh(CMeshO&, vcg::tri::IsotropicRemeshing<CMeshO>::Params&) (params=..., m=...) at /usr/include/c++/8/ext/new_allocator.h:86
#8  0x00007fff94f65ab3 in vcg::tri::IsotropicRemeshing<CMeshO>::Do(CMeshO&, CMeshO&, vcg::tri::IsotropicRemeshing<CMeshO>::Params&, bool (*)(int, char const*)) (toRemesh=..., toProject=..., params=..., cb=cb@entry=0x55555561f500 <MainWindow::QCallBack(int, char const*)>) at ./vcglib/vcg/complex/algorithms/isotropic_remeshing.h:252
#9  0x00007fff94f0b3f3 in ExtraMeshFilterPlugin::applyFilter(QAction*, MeshDocument&, RichParameterSet&, bool (*)(int, char const*)) (this=0x555556634650, filter=<optimized out>, md=..., par=..., cb=0x55555561f500 <MainWindow::QCallBack(int, char const*)>) at ./src/meshlabplugins/filter_meshing/meshfilter.cpp:974
#10 0x0000555555633f7a in MainWindow::executeFilter(QAction*, RichParameterSet&, bool) (this=0x7fffffffde50, action=0x555556639c40, params=..., isPreview=<optimized out>) at ./src/meshlab/mainwindow.h:367
#11 0x000055555565cc76 in MeshlabStdDialog::applyClick() (this=0x555556f156a0) at ./src/meshlab/ml_std_par_dialog.cpp:214
#12 0x00007ffff67737f6 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff7751602 in QAbstractButton::clicked(bool) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff775181a in  () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7752bdf in  () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7752db5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff76a94d8 in QWidget::event(QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff766b4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff7672bb8 in QApplication::notify(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7f6a25a in MeshLabApplication::notify(QObject*, QEvent*) (this=<optimized out>, rec=<optimized out>, ev=<optimized out>) at ./src/common/mlapplication.cpp:8
#21 0x00007ffff674a489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff7671ee9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff76c3fd4 in  () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff76c6b5e in  () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff766b4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff7672970 in QApplication::notify(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff7f6a25a in MeshLabApplication::notify(QObject*, QEvent*) (this=<optimized out>, rec=<optimized out>, ev=<optimized out>) at ./src/common/mlapplication.cpp:8
#28 0x00007ffff674a489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff709bff3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Gui.so.5
#30 0x00007ffff709de75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007ffff707806b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Gui.so.5
#32 0x00007ffff2c8a40b in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#33 0x00007ffff674915b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff6751132 in QCoreApplication::exec() () at /usr/bin/../lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00005555555caeae in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe528) at ./src/meshlab/main.cpp:90
```

To a normal user this would look like a crash.

[softjaw2.zip](https://github.com/cnr-isti-vclab/meshlab/files/4462376/softjaw2.zip)

This did provoke some solvespace warnings when exporting:
![image](https://user-images.githubusercontent.com/61129/79005889-81319600-7b1d-11ea-9e88-65ceb9bbe5b2.png)

However, its predecessor design had an inexplicable gap that only appeared in the STL.

**Comment by alemuntoni** [comment]
Apparently his issue has been fixed in some of the previous commit!
