### ISSUE TITLE
Meshlab segfaults when .mlp matrices don't have trailing spaces before newlines

### ISSUE THREAD

**Issue by nh2** [cnr-isti-vclab/meshlab#913]
If you edit an `.mlp` file saved by meshlab, and your editor removes trailing spaces from e.g. this:

```
   <MLMatrix44>
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 
</MLMatrix44>
```

into this:

```
   <MLMatrix44>
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
</MLMatrix44>
```

then meshlab 2020.07 will segfault.

* Meshlab should not segfault on invalid data; it should print an error message to tell the user what's wrong.
* Ideally meshlab would also accept `.mlp` files without trailing spaces.

`gdb` backtrace that shows the involved code:

```c
0x00007ffff670f352 in QString::toDouble(bool*) const () from /nix/store/4b5anxjaqajvvkk242pf8mv4k2w0z49r-qtbase-5.15.2/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff670f352 in QString::toDouble(bool*) const () from /nix/store/4b5anxjaqajvvkk242pf8mv4k2w0z49r-qtbase-5.15.2/lib/libQt5Core.so.5
#1  0x00007ffff670f38d in QString::toFloat(bool*) const () from /nix/store/4b5anxjaqajvvkk242pf8mv4k2w0z49r-qtbase-5.15.2/lib/libQt5Core.so.5
#2  0x00007ffff7f6c30a in MeshDocumentFromXML(MeshDocument&, QString, bool, std::map<int, MLRenderingData, std::less<int>, std::allocator<std::pair<int const, MLRenderingData> > >&) ()
   from /nix/store/riw0ny1fhmhl74z9d0m8ixp55p33zns4-meshlab-2020.07/lib/meshlab/libmeshlab-common.so
#3  0x00000000004af700 in MainWindow::openProject(QString) ()
#4  0x000000000044a585 in main ()
```

**Comment by alemuntoni** [comment]
Thanks for reporting this. The fix will be available in the next meshlab version.
